### ISSUE TITLE
Create client is error!!!

### ISSUE THREAD

**Issue by ruanqunfeng** [binance-chain/java-sdk#46]
![image](https://user-images.githubusercontent.com/15098545/59577584-eaf83380-90f6-11e9-8593-0a5dce1e9d24.png)

**Comment by fletcher142** [comment]
please try to use "BinanceDexApiClientFactory.newInstance().**newRestClient**(BinanceDexEnvironment.TEST_NET.getBaseUrl())"  to get the instance of BinanceDexApiRestClient instead of using "newNodeRpcClient".
Or using "BinanceDexEnvironment.TEST_NET_NODE.getBaseUrl()" for the 1st param if you want to query things via node rpc.i.e., 
BinanceDexApiClientFactory.newInstance().**newNodeRpcClient**(BinanceDexEnvironment.TEST_NET_NODE.getBaseUrl(), BinanceDexEnvironment.TEST_NET_NODE.getHrp()).

**Comment by ruanqunfeng** [comment]
> BinanceDexApiClientFactory.newInstance().**newRestClient**(BinanceDexEnvironment.TEST_NET.getBaseUrl())

![image](https://user-images.githubusercontent.com/15098545/59666261-165a4b80-91e7-11e9-917e-ad5f52a8035e.png)

Also has this error!!!

**Comment by fletcher142** [comment]
Probably there are some conflicts with okhttp3 library in your project.The version of okhttp3 which java-sdk uses is 3.12.0. pls check that with 'mvn dependency:tree', and exculde the other one.
