### ISSUE TITLE
getAccount is NullPointerException

### ISSUE THREAD

**Issue by huzongcai** [binance-chain/java-sdk#48]
![1560860412](https://user-images.githubusercontent.com/44515976/59681523-b6739d00-9206-11e9-8f54-26daddb35bd1.jpg)

**Comment by fletcher142** [comment]
"BinanceDexEnvironment.PROD.getBaseUrl()" is for rest call,not for rpc. We should connect to dataseed node if we want to access node via rpc. There are several dataseed nodes you can see 
 on [](https://dex.binance.org/api/v1/peers). So you can instantiate nodeclient,like blew：
`BinanceDexApiNodeClient client = BinanceDexApiClientFactory.newInstance().newNodeRpcClient("https://dataseed3.ninicoin.io:443","bnb");`

In addition, the NPE would be fixed in next release.

**Comment by huzongcai** [comment]
thank you
