### ISSUE TITLE
How to get all transactions in a block？

### ISSUE THREAD

**Issue by wangke0809** [binance-chain/java-sdk#57]
```https://testnet-explorer.binance.org/block/29848066```
I found block 29848066 of the test net has 118 transactions, but `getBlockTransactions` only get 30 transactions. How to get all of them?

**Comment by fletcher142** [comment]
It is fixed now.plz try again

**Comment by wangke0809** [comment]
> It is fixed now.plz try again

Thanks! I found sth wrong. The max value of per page should be 100. And we should also know the total number of page.

**Comment by fletcher142** [comment]
> > It is fixed now.plz try again
> 
> Thanks! I found sth wrong. The max value of per page should be 100. And we should also know the total number of page.

Thanks for your advice. This `getBlockTransactions` api is designed to provide an entrance to get all transactions in a block.Because of the limitation of size of block, there would not be so much txs in a block.
In addition, an api of fetching transactions with pagination will be added in the future, and let client fill in page size and page number as parameter.
