### ISSUE TITLE
use java sdk always got error: no secp256k1 in java.library.path

### ISSUE THREAD

**Issue by perterest** [binance-chain/java-sdk#65]
when i use binance java sdk in my project, when i call BinanceDexApiRestClient#transfer method, but always got error: 

org.bitcoin.Secp256k1Context: java.lang.UnsatisfiedLinkError: no secp256k1 in java.library.path

please help me.

**Comment by fletcher142** [comment]
Generally, it is expect that can't find `secp256k1`.But it wont affect using this SDK to generate signature when you try sending a transaction to block chain.So if your transfer didn't succeed, it must be another error in you project.

BTW as we know, elliptic curve math is used for creating signatures to spend transactions, and for validating signatures in transactions that you receive from the network. And `libsecp256k1` is a heavily optimized library for doing elliptic curve math.But we don't need this lib at all because we have it implemented in our dependency of `bcprov-jdk15on` which is imported by `bitcoinj-core`.

However it is possible that you wanna use `secp256k1`, please refer to https://bitcoinj.github.io/javadoc/0.14/org/bitcoin/NativeSecp256k1.html.
